### ISSUE TITLE
Load more in Follow list

### ISSUE THREAD

**Issue by rafaell-lycan** [tadeuzagallo/GithubPulse#39] opened 2015-02-04 15:19 UTC
In "users I'm following" set a limit (like 20) and add a button to load some others.

The load about other user are damn slow.

I don't know if this is a better idea, but maybe resolve the problem about load that info.

**Comment by tadeuzagallo** [comment] 2015-02-05 13:46
Duplicate of #36

**Closed as completed by tadeuzagallo** 2015-02-05 13:46 UTC
